### ISSUE TITLE
New release for 1.2-8?

### ISSUE THREAD

**Issue by seth127** [RobinHankin/Brobdingnag#24]
Hello,
First off, thank you for continuing to maintain this package! Very useful.

I'm wondering if are planning to make a `1.2.-8` and/or to submit the current version of the package to CRAN?

I ask because I am having a similar issue to the one described [here](https://github.com/tidyverse/dbplyr/issues/779) and it looks like you fixed that problem [here](https://github.com/RobinHankin/Brobdingnag/pull/21). However, the version on CRAN still doesn't have that fix.

Is there a (development-related) reason that you haven't submitted to CRAN or tagged `1.2-8` release? I'm basically trying to figure out if the code on `master` still has some things in flight, or if I should just install directly from there.

Thanks again!
Seth

**Comment by RobinHankin** [comment]
Hello Seth

no particular reason for not submitting to CRAN other than laziness and/or forgetfulness.  The `master` branch is now clean under `R CMD check` AFAICS and I've just run `revdep_check()` [which takes much longer these days, more dependencies!] and verified that it's clean under winbuilder.

Anyway, I uploaded 1.2-8 to CRAN just now, here's hoping it goes through with no problems.  I'll add a tag if it does.

Best wishes

Robin

**Comment by RobinHankin** [comment]
problems on submission to CRAN.   According to Uwe,  1.2-8 is clean under windows but returns a WARNING under debian:

package Brobdingnag_1.2-8.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/Brobdingnag_1.2-8_20221003_214419/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/Brobdingnag_1.2-8_20221003_214419/Debian/00check.log>
Status: 1 WARNING


Quite difficult to diagnose remotely but here is the report: 

```
[snip]
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... [2s/2s] OK
  Running ‘testthat.R’ [2s/2s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... [5s/5s] WARNING
Error(s) in re-building vignettes:
  ...
--- re-building ‘Brobdingnag.Rnw’ using Sweave
Loading required package: Brobdingnag
Loading required package: Matrix

Attaching package: ‘Brobdingnag’

The following objects are masked from ‘package:Matrix’:

    diag, t

The following objects are masked from ‘package:base’:

    diag, t

Error: processing vignette ‘Brobdingnag.Rnw’ failed with diagnostics:
Running ‘texi2dvi’ on ‘Brobdingnag.tex’ failed.
LaTeX errors:
! LaTeX Error: File `' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
! Emergency stop.
 ...                                              
                                                  
l.48 \includegraphics[width=1in]{}
                                  
!  ==> Fatal error occurred, no output PDF file produced!
--- failed re-building ‘Brobdingnag.Rnw’

--- re-building ‘S4_brob.Rnw’ using Sweave
--- finished re-building ‘S4_brob.Rnw’

SUMMARY: processing the following file failed:
  ‘Brobdingnag.Rnw’

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... [3s/3s] OK
* checking HTML version of manual ... [0s/0s] OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 WARNING
```

I suspect that the `wrapfig`  package used in commit 2692c89485794e07b16e2ac9bf2a96ce30818cf0 is the cause of the problem, am investigating

**Comment by RobinHankin** [comment]
reverse dependency problems are delaying upload to CRAN: see issue #24

**Comment by RobinHankin** [comment]
Uwe asked me what was going on and I replied to him and cran-SUBMISSIONS@r-project.org just now:


Thanks for this Uwe, and sorry for the lack of communication.

I am having architecture-dependent reports from revdep_check() and indeed winbuilder and this is taking longer than I expected to sort out.  Another problem was the availability of Matrix_1.5-0 which was causing problems.

I had not realised that a human being was involved in this part of the flowchart!  My thinking was to wait for "roughly seven days" for the log files to be removed, and then try again with a new submission which I will name Brobdingnag_1.2-9.

Please expunge Brobdingnag_1.2-8 while I sort all this lot out.

best wishes

Robin

**Comment by snikumbh** [comment]
Hi @RobinHankin 

I was wondering if you have an estimate or when you think you will be able to devote time to resolve this? 
Appreciate your work/contribution.

Thanks in advance.

**Comment by RobinHankin** [comment]
I uploaded 1.2-9 to CRAN just now: clean under winbuilder R-release and R-devel.  Clean under `revdep_check()` on ubuntu linux but the tests could not complete on my desktop (mac os X)  due to some C library error, which I could not fix despite a lot of effort.  Also, I could not even install 1.2-9 on Bob (a virtual ubuntu linux box), due to its not being able to process the vignettes.   Could not fix this either, despite a *lot* of effort.

Email from CRAN follows:

Dear maintainer,

package Brobdingnag_1.2-9.tar.gz has been auto-processed and is pending an automated reverse dependency check. This service will typically respond to you within the next day. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

Log dir: <https://win-builder.r-project.org/incoming_pretest/Brobdingnag_1.2-9_20221019_110831/>
The files will be removed after roughly 7 days.
Installation time in seconds: 31
Check time in seconds: 202
R Under development (unstable) (2022-10-11 r83083 ucrt)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/Brobdingnag_1.2-9_20221019_110831/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/Brobdingnag_1.2-9_20221019_110831/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 13
See: <https://cran.r-project.org/web/checks/check_results_Brobdingnag.html>

CRAN Web: <https://cran.r-project.org/package=Brobdingnag>

*** Strong rev. depends ***: BMTAR bridgesampling eBsc gmvarkit momentuHMM MPTinR multibridge multimark uGMAR untb

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Robin K. S. Hankin <[hankin.robin@gmail.com](mailto:hankin.robin@gmail.com)>'

**Comment by snikumbh** [comment]
Fingers crossed! 
Appreciate your efforts!

**Comment by snikumbh** [comment]
I think everything worked, and 1.2-9 is on CRAN! 
Thanks @RobinHankin

**Comment by RobinHankin** [comment]
yes, I got the confirmation this morning!

**Comment by seth127** [comment]
Just coming around again to say thanks for jumping on this so quickly @RobinHankin ! All of our previous issues seem to be fixed with the new release. We appreciate your work here.
